### ISSUE TITLE
gpg: keyserver receive failed: No route to host

### ISSUE THREAD

**Issue by Plippe** [gilt/okta-aws-login#2]
Hey,

Just ran the install script as the readme states, `curl -L https://raw.githubusercontent.com/gilt/okta-aws-login/master/install | /bin/bash`, but this raises a lovely error from gpg, `gpg: keyserver receive failed: No route to host`.

The issue is that gpg isn't able to find the ip to `keys.gnupg.net`. An easy fix is to hard code that address, but that wouldn't be smart. An nslookup, and a bit of bash is better.

```sh
ADDRESS=$(nslookup -type=cname keys.gnupg.net | grep 'internet address' | cut -d' ' -f4 | head -n1)
gpg --keyserver $ADDRESS --recv-key 0x3C35F6BBA50B5999
```

**Comment by Plippe** [comment]
https://github.com/gilt/okta-aws-login/pull/3

**Comment by andreyk0** [comment]
Thanks!

It seems the actual issue is IPv6. There are many people running into same problem with latest gpg.
Key pool servers now have IPv6 nodes in them and they seem to be tried first (and fail).

I'll see if there's a better accepted workaround, if not - we'll merge your patch.

**Comment by andreyk0** [comment]
Seems that this could work instead: `hkp://ipv4.pool.sks-keyservers.net:80`.
I'll close this issue/PR and update script with that.
