### ISSUE TITLE
Unable to find SAMLResponse in the output of Response

### ISSUE THREAD

**Issue by andylockran** [gilt/okta-aws-login#4]
okta-aws-login: Unable to find SAMLResponse in the output of Response.

I have an account setup with MFA - it successfully challenges me for a token, but then finishes with this error.  There appears to be html/js output to the screen, ```error, called at src/OktaClient.hs:117:19 in main:OktaClient```

**Comment by andreyk0** [comment]
Hi!
This integration actually relies on parsing a field named `SAMLResponse` from HTML. Haven't checked recently but at the time of writing all Okta/AWS integrations I'd seen worked similarly.

This error most likely means that Okta account settings are incompatible with AWS CLI integration.
If I remember things correctly, last time we've run into this error with one of our accounts some Okta verification rules were configured on an account level and that broke integration. After a support call with Okta we reconfigured checks to be done on the global level exclusively.

BTW, AWS recently announced their own SAML solution: https://github.com/awslabs/awsprocesscreds

**Comment by andylockran** [comment]
Thanks very much for that.  It's getting stuck on MFA using that tool - but have already started implementing that tonight, so should be fairly straightforward to get that working, and a PR submitted.

Thanks for your direction :)
